apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: base-postgresha-cluster
spec:
  teamId: "acid"
  volume:
    size: 10Gi
    storageClass: hostpath
  numberOfInstances: 3
  users:
    arsa_test: # database owner
      - superuser
      - createdb
    arsa_test_db1_user: [] # role for application arsa_test_db1
  databases:
    arsa_test_db1: arsa_test_db1_user # dbname: owner
  # preparedDatabases:
  #   bar: {}
  postgresql:
    version: "15"

  resources:
    requests:
      # cpu: 100m
      memory: 5Gi

  sidecars:
    - name: "exporter"
      image: "quay.io/prometheuscommunity/postgres-exporter:latest"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 200M
      env:
        - name: "DATA_SOURCE_URI"
          value: 127.0.0.1:5432
        - name: "DATA_SOURCE_USER"
          value: "$(POSTGRES_USER)"
        - name: "DATA_SOURCE_PASS"
          value: "$(POSTGRES_PASSWORD)"
        - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
          value: "true"
