#version: "3.9"

services:
  web1:
    build:
      context: ./P3-juanlu-apache
      dockerfile: DockerfileApacheP3
    image: juanlu-apache-image:p3
    container_name: web1
    ports:
      - "8080:80"
      - "9080:443"
    volumes:
      - ./web_juanlu:/var/www/html/
      - ./P3-juanlu-certificados:/etc/apache2/ssl/
      - ./P3-juanlu-apache/juanlu-apache-ssl.conf:/etc/apache2/sites-available/juanlu-apache-ssl.conf

    networks:
      red_web:
        ipv4_address: 192.168.10.2 
      red_servicios:
        ipv4_address: 192.168.20.2 
  web2:
    build:
      context: ./P3-juanlu-apache
      dockerfile: DockerfileApacheP3
    image: juanlu-apache-image:p3
    container_name: web2
    ports:
      - "8081:80"
      - "9081:443"
    volumes:
      - ./web_juanlu:/var/www/html/
      - ./P3-juanlu-certificados:/etc/apache2/ssl/
      - ./P3-juanlu-apache/juanlu-apache-ssl.conf:/etc/apache2/sites-available/juanlu-apache-ssl.conf

    networks:
      red_web:
        ipv4_address: 192.168.10.3 
      red_servicios:
        ipv4_address: 192.168.20.3 
  web3:
    build:
      context: ./P3-juanlu-apache
      dockerfile: DockerfileApacheP3
    image: juanlu-apache-image:p3
    container_name: web3
    ports:
      - "8082:80"
      - "9082:443"
    volumes:
      - ./web_juanlu:/var/www/html/
      - ./P3-juanlu-certificados:/etc/apache2/ssl/
      - ./P3-juanlu-apache/juanlu-apache-ssl.conf:/etc/apache2/sites-available/juanlu-apache-ssl.conf

    networks:
      red_web:
        ipv4_address: 192.168.10.4 
      red_servicios:
        ipv4_address: 192.168.20.4 
  web4:
    build:
      context: ./P3-juanlu-apache
      dockerfile: DockerfileApacheP3
    image: juanlu-apache-image:p3
    container_name: web4
    ports:
      - "8083:80"
      - "9083:443"
    volumes:
      - ./web_juanlu:/var/www/html/
      - ./P3-juanlu-certificados:/etc/apache2/ssl/
      - ./P3-juanlu-apache/juanlu-apache-ssl.conf:/etc/apache2/sites-available/juanlu-apache-ssl.conf

    networks:
      red_web:
        ipv4_address: 192.168.10.5 
      red_servicios:
        ipv4_address: 192.168.20.5
  
  balanceador-nginx-ssl:
    build:
      context: ./P3-juanlu-nginx
      dockerfile: DockerfileNginxP3
    image: juanlu-nginx-image:p3
    container_name: balanceador-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./P3-juanlu-nginx/juanlu-nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./P3-juanlu-certificados:/etc/nginx/ssl/
    networks:
      red_web:
        ipv4_address: 192.168.10.50 
    depends_on:
      - web1
      - web2
      - web3
      - web4
 
networks:
  red_web:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_servicios:
    ipam:
      config:
        - subnet: 192.168.20.0/24
