services:
  apache-benchmark-P5:
    build:
      context: .
      dockerfile: DockerFileAB
    image: juanluis-ab-image:p5
    container_name: apache_benchmark-P5
    #command: ["ab", "-n", "10000", "-c", "100", "https://192.168.10.50:443/"]
    command: ["ab", "-n", "10000", "-c", "100", "https://localhost:4000/"]
    networks:
      red_web:
        ipv4_address: 192.168.10.60

networks:
  red_web:
    external: true  